services:
  line-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: pnpm start:dev
    ports:
      - '3001:3001'
    volumes:
      - ./:/app
      - /app/node_modules
      - ./config:/app/config
    depends_on:
      - postgres
    networks:
      - line-service-network
  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: booking-line-service
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - line-service-network

volumes:
  postgres-data:

networks:
  line-service-network:
    driver: bridge
